# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_revision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ('created_at',), 'verbose_name': 'Revision', 'verbose_name_plural': 'Revisions'},
        ),
    ]
